services:
  - type: web
    name: dely-api
    dockerfilePath: Dockerfile
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: PIP_NO_BUILD_ISOLATION
        value: "1"
      - key: PIP_ONLY_BINARY
        value: ":all:"
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: dely-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
    healthCheckPath: /health

databases:
  - name: dely-db
    databaseName: dely_db
    user: dely_user
    plan: free

